version: '2.3'

services:
    naviserver_rp:
        image: logansw/naviserver:v1.8
        container_name: rp_test_naviserver_rp
        restart: unless-stopped
        command: "/usr/local/ns/bin/nsd -i -u root -g web -t /web/etc/nsd-config-revproxy.tcl"
        volumes:
            - ./etc:/web/etc
            - ./logs:/web/logs
            - ${CERTSPATH}:/web/certs:ro
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 127.0.0.1:18090:18090
            - 127.0.0.1:48090:48090
        environment:
            - TZ=America/Denver
        networks:
            - default
    naviserver_be:
        image: logansw/naviserver:v1.8
        container_name: rp_test_naviserver_be
        restart: unless-stopped
        command: bash -c "/usr/local/ns/bin/nsd -u root -g web -t /web/etc/nsd-config-backend.tcl &&
                          /usr/local/ns/bin/nsd -i -u root -g web -t /web/etc/nsd-config-sc-revproxy.tcl"
        volumes:
            - ./etc:/web/etc
            - ./logs:/web/logs
            - ${CERTSPATH}:/web/certs:ro
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 127.0.0.1:18091:18091
            - 127.0.0.1:18099:18099
            - 127.0.0.1:48099:48099
        environment:
            - TZ=America/Denver
        networks:
            - default

networks:
    default:
        external:
            name: rp-network
